// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfbRSCyE8H2j9jggOIUI-Gh-a1CoqJ9WA',
    appId: '1:579653135558:web:fdbf6747fbada14ac57bc7',
    messagingSenderId: '579653135558',
    projectId: 'shoplist-9f307',
    authDomain: 'shoplist-9f307.firebaseapp.com',
    storageBucket: 'shoplist-9f307.appspot.com',
    measurementId: 'G-7J357YE6J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtlPxnf7KqREjL-mLE_o40kPTrJj-eSu4',
    appId: '1:579653135558:android:4c26f02ca769481dc57bc7',
    messagingSenderId: '579653135558',
    projectId: 'shoplist-9f307',
    storageBucket: 'shoplist-9f307.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ0e2nR2G5Gxdu6qF1z-_KVg_CST8cvMQ',
    appId: '1:579653135558:ios:6766809e4ef6eed5c57bc7',
    messagingSenderId: '579653135558',
    projectId: 'shoplist-9f307',
    storageBucket: 'shoplist-9f307.appspot.com',
    iosClientId: '579653135558-j9und1jr4vf4hdaof7opm4ho8c1a3364.apps.googleusercontent.com',
    iosBundleId: 'org.luisciber.shoplist',
  );
}
